application: no-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: compiler.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest